// Vocabulary database — COCO-SSD detectable object labels
// Translations: en, fr, es, ja, hi (Hindi), mr (Marathi), ar (Arabic)

const VOCABULARY = {
  person: {
    word: 'Person', phonetic: '/ˈpɜː.sən/', pos: 'noun',
    definition: 'A human being regarded as an individual.',
    example: 'A person was walking down the street.',
    translations: { en: 'Person', fr: 'Personne', es: 'Persona', ja: '人 (hito)', hi: 'व्यक्ति (vyakti)', mr: 'व्यक्ती (vyakti)', ar: 'شخص (shakhs)' },
    color: '#e91e8c',
  },
  bicycle: {
    word: 'Bicycle', phonetic: '/ˈbaɪ.sɪ.kəl/', pos: 'noun',
    definition: 'A vehicle with two wheels moved by pedaling.',
    example: 'She rides her bicycle to school every day.',
    translations: { en: 'Bicycle', fr: 'Vélo', es: 'Bicicleta', ja: '自転車 (jitensha)', hi: 'साइकिल (saikil)', mr: 'सायकल (saikal)', ar: 'دراجة (darraja)' },
    color: '#3f51b5',
  },
  car: {
    word: 'Car', phonetic: '/kɑːr/', pos: 'noun',
    definition: 'A road vehicle powered by an engine, typically with four wheels.',
    example: 'He drives his car to work every morning.',
    translations: { en: 'Car', fr: 'Voiture', es: 'Coche', ja: '車 (kuruma)', hi: 'गाड़ी (gaadi)', mr: 'गाडी (gaadi)', ar: 'سيارة (sayyara)' },
    color: '#f44336',
  },
  motorcycle: {
    word: 'Motorcycle', phonetic: '/ˈməʊ.tə.saɪ.kəl/', pos: 'noun',
    definition: 'A two-wheeled motor vehicle.',
    example: 'The motorcycle sped down the highway.',
    translations: { en: 'Motorcycle', fr: 'Moto', es: 'Motocicleta', ja: 'バイク (baiku)', hi: 'मोटरसाइकिल (motorsaikil)', mr: 'मोटारसायकल (motarsaikal)', ar: 'دراجة نارية (darraja nariyya)' },
    color: '#ff5722',
  },
  bus: {
    word: 'Bus', phonetic: '/bʌs/', pos: 'noun',
    definition: 'A large motor vehicle carrying passengers along a fixed route.',
    example: 'We took the bus to the city center.',
    translations: { en: 'Bus', fr: 'Bus', es: 'Autobús', ja: 'バス (basu)', hi: 'बस (bas)', mr: 'बस (bas)', ar: 'حافلة (hafila)' },
    color: '#ff9800',
  },
  truck: {
    word: 'Truck', phonetic: '/trʌk/', pos: 'noun',
    definition: 'A large, heavy motor vehicle for transporting goods.',
    example: 'The truck delivered boxes to the warehouse.',
    translations: { en: 'Truck', fr: 'Camion', es: 'Camión', ja: 'トラック (torakku)', hi: 'ट्रक (trak)', mr: 'ट्रक (trak)', ar: 'شاحنة (shahina)' },
    color: '#795548',
  },
  bench: {
    word: 'Bench', phonetic: '/bentʃ/', pos: 'noun',
    definition: 'A long seat for several people, typically made of wood.',
    example: 'They sat on a bench in the park.',
    translations: { en: 'Bench', fr: 'Banc', es: 'Banco', ja: 'ベンチ (benchi)', hi: 'बेंच (bench)', mr: 'बाक (baak)', ar: 'مقعد (maq\'ad)' },
    color: '#8bc34a',
  },
  bird: {
    word: 'Bird', phonetic: '/bɜːrd/', pos: 'noun',
    definition: 'A warm-blooded animal with wings, feathers, and a beak.',
    example: 'A bird sang beautifully in the tree.',
    translations: { en: 'Bird', fr: 'Oiseau', es: 'Pájaro', ja: '鳥 (tori)', hi: 'पक्षी (pakshi)', mr: 'पक्षी (pakshi)', ar: 'طائر (ta\'ir)' },
    color: '#00bcd4',
  },
  cat: {
    word: 'Cat', phonetic: '/kæt/', pos: 'noun',
    definition: 'A small domesticated carnivorous mammal with soft fur.',
    example: 'The cat curled up on the sofa.',
    translations: { en: 'Cat', fr: 'Chat', es: 'Gato', ja: '猫 (neko)', hi: 'बिल्ली (billi)', mr: 'मांजर (manjar)', ar: 'قطة (qitta)' },
    color: '#9c27b0',
  },
  dog: {
    word: 'Dog', phonetic: '/dɒɡ/', pos: 'noun',
    definition: 'A domesticated carnivorous mammal, often kept as a pet.',
    example: 'The dog wagged its tail happily.',
    translations: { en: 'Dog', fr: 'Chien', es: 'Perro', ja: '犬 (inu)', hi: 'कुत्ता (kutta)', mr: 'कुत्रा (kutra)', ar: 'كلب (kalb)' },
    color: '#ff9800',
  },
  horse: {
    word: 'Horse', phonetic: '/hɔːrs/', pos: 'noun',
    definition: 'A large four-legged animal used for riding or pulling loads.',
    example: 'The horse galloped across the field.',
    translations: { en: 'Horse', fr: 'Cheval', es: 'Caballo', ja: '馬 (uma)', hi: 'घोड़ा (ghoda)', mr: 'घोडा (ghoda)', ar: 'حصان (hisan)' },
    color: '#795548',
  },
  sheep: {
    word: 'Sheep', phonetic: '/ʃiːp/', pos: 'noun',
    definition: 'A domesticated ruminant animal with a thick woolly coat.',
    example: 'The sheep grazed quietly on the hillside.',
    translations: { en: 'Sheep', fr: 'Mouton', es: 'Oveja', ja: '羊 (hitsuji)', hi: 'भेड़ (bhed)', mr: 'मेंढी (mendhi)', ar: 'خروف (kharuf)' },
    color: '#9e9e9e',
  },
  cow: {
    word: 'Cow', phonetic: '/kaʊ/', pos: 'noun',
    definition: 'A fully grown female bovine animal kept for milk or beef.',
    example: 'The cow stood in the field chewing grass.',
    translations: { en: 'Cow', fr: 'Vache', es: 'Vaca', ja: '牛 (ushi)', hi: 'गाय (gaay)', mr: 'गाय (gaay)', ar: 'بقرة (baqara)' },
    color: '#607d8b',
  },
  elephant: {
    word: 'Elephant', phonetic: '/ˈel.ɪ.fənt/', pos: 'noun',
    definition: 'A very large mammal with a trunk and tusks.',
    example: 'The elephant splashed water with its trunk.',
    translations: { en: 'Elephant', fr: 'Éléphant', es: 'Elefante', ja: '象 (zou)', hi: 'हाथी (haathi)', mr: 'हत्ती (hatti)', ar: 'فيل (fil)' },
    color: '#607d8b',
  },
  bear: {
    word: 'Bear', phonetic: '/beər/', pos: 'noun',
    definition: 'A large, heavy mammal with thick fur and a short tail.',
    example: 'The bear searched for honey in the forest.',
    translations: { en: 'Bear', fr: 'Ours', es: 'Oso', ja: '熊 (kuma)', hi: 'भालू (bhaalu)', mr: 'अस्वल (aswal)', ar: 'دب (dubb)' },
    color: '#795548',
  },
  zebra: {
    word: 'Zebra', phonetic: '/ˈziː.brə/', pos: 'noun',
    definition: 'An African wild animal similar to a horse with black and white stripes.',
    example: 'The zebra roamed freely on the savanna.',
    translations: { en: 'Zebra', fr: 'Zèbre', es: 'Cebra', ja: 'シマウマ (shimauma)', hi: 'ज़ेब्रा (zebra)', mr: 'झेब्रा (zebra)', ar: 'حمار وحشي (himar wahshi)' },
    color: '#212121',
  },
  giraffe: {
    word: 'Giraffe', phonetic: '/dʒɪˈrɑːf/', pos: 'noun',
    definition: 'A tall African mammal with a very long neck and spotted coat.',
    example: 'The giraffe reached leaves high in the tree.',
    translations: { en: 'Giraffe', fr: 'Girafe', es: 'Jirafa', ja: 'キリン (kirin)', hi: 'जिराफ़ (jiraf)', mr: 'जिराफ (jiraf)', ar: 'زرافة (zarafa)' },
    color: '#ff9800',
  },
  backpack: {
    word: 'Backpack', phonetic: '/ˈbæk.pæk/', pos: 'noun',
    definition: 'A bag with shoulder straps carried on the back.',
    example: 'She packed her books into the backpack.',
    translations: { en: 'Backpack', fr: 'Sac à dos', es: 'Mochila', ja: 'リュック (ryukku)', hi: 'बैगपैक (bagpack)', mr: 'सॅक (sak)', ar: 'حقيبة ظهر (haqibat zahr)' },
    color: '#3f51b5',
  },
  umbrella: {
    word: 'Umbrella', phonetic: '/ʌmˈbrel.ə/', pos: 'noun',
    definition: 'A device used as protection from rain, with a circular canopy.',
    example: 'He opened his umbrella as it started to rain.',
    translations: { en: 'Umbrella', fr: 'Parapluie', es: 'Paraguas', ja: '傘 (kasa)', hi: 'छाता (chhata)', mr: 'छत्री (chhatri)', ar: 'مظلة (mizalla)' },
    color: '#2196f3',
  },
  handbag: {
    word: 'Handbag', phonetic: '/ˈhænd.bæɡ/', pos: 'noun',
    definition: 'A small bag used especially by women to carry everyday items.',
    example: 'She searched for her keys in her handbag.',
    translations: { en: 'Handbag', fr: 'Sac à main', es: 'Bolso', ja: 'ハンドバッグ (handobaggu)', hi: 'हैंडबैग (handbag)', mr: 'पर्स (pars)', ar: 'حقيبة يد (haqibat yad)' },
    color: '#e91e8c',
  },
  suitcase: {
    word: 'Suitcase', phonetic: '/ˈsuːt.keɪs/', pos: 'noun',
    definition: 'A rectangular case with a handle, used for carrying clothes while travelling.',
    example: 'She packed her suitcase the night before the trip.',
    translations: { en: 'Suitcase', fr: 'Valise', es: 'Maleta', ja: 'スーツケース (suutsukeesu)', hi: 'सूटकेस (suitcase)', mr: 'सूटकेस (suitcase)', ar: 'حقيبة سفر (haqibat safar)' },
    color: '#607d8b',
  },
  bottle: {
    word: 'Bottle', phonetic: '/ˈbɒt.əl/', pos: 'noun',
    definition: 'A glass or plastic container for liquids with a narrow neck.',
    example: 'She drank from a bottle of water.',
    translations: { en: 'Bottle', fr: 'Bouteille', es: 'Botella', ja: 'ボトル (botoru)', hi: 'बोतल (botal)', mr: 'बाटली (baatli)', ar: 'زجاجة (zujaja)' },
    color: '#009688',
  },
  'wine glass': {
    word: 'Wine Glass', phonetic: '/waɪn ɡlɑːs/', pos: 'noun',
    definition: 'A glass with a stem, used for drinking wine.',
    example: 'He raised his wine glass in a toast.',
    translations: { en: 'Wine Glass', fr: 'Verre à vin', es: 'Copa de vino', ja: 'ワイングラス (waingurasu)', hi: 'वाइन ग्लास (wine glass)', mr: 'वाईन ग्लास (wine glass)', ar: 'كأس نبيذ (ka\'s nabidh)' },
    color: '#9c27b0',
  },
  cup: {
    word: 'Cup', phonetic: '/kʌp/', pos: 'noun',
    definition: 'A small bowl-shaped container for drinking.',
    example: 'She enjoyed a cup of tea in the morning.',
    translations: { en: 'Cup', fr: 'Tasse', es: 'Taza', ja: 'カップ (kappu)', hi: 'कप (kap)', mr: 'कप (kap)', ar: 'كوب (koob)' },
    color: '#ff9800',
  },
  fork: {
    word: 'Fork', phonetic: '/fɔːrk/', pos: 'noun',
    definition: 'A utensil with prongs used for eating food.',
    example: 'He used a fork to eat his pasta.',
    translations: { en: 'Fork', fr: 'Fourchette', es: 'Tenedor', ja: 'フォーク (fooku)', hi: 'काँटा (kaanta)', mr: 'काटा (kaata)', ar: 'شوكة (shawka)' },
    color: '#9e9e9e',
  },
  knife: {
    word: 'Knife', phonetic: '/naɪf/', pos: 'noun',
    definition: 'A cutting utensil with a sharp blade and handle.',
    example: 'She used a knife to cut the bread.',
    translations: { en: 'Knife', fr: 'Couteau', es: 'Cuchillo', ja: 'ナイフ (naifu)', hi: 'चाकू (chaaku)', mr: 'सुरी (suri)', ar: 'سكين (sikkeen)' },
    color: '#9e9e9e',
  },
  spoon: {
    word: 'Spoon', phonetic: '/spuːn/', pos: 'noun',
    definition: 'A utensil with a round bowl and handle, used for eating liquids.',
    example: 'She stirred the soup with a spoon.',
    translations: { en: 'Spoon', fr: 'Cuillère', es: 'Cuchara', ja: 'スプーン (supuun)', hi: 'चम्मच (chammach)', mr: 'चमचा (chamcha)', ar: 'ملعقة (mil\'aqa)' },
    color: '#9e9e9e',
  },
  bowl: {
    word: 'Bowl', phonetic: '/bəʊl/', pos: 'noun',
    definition: 'A round, deep dish used for food or liquids.',
    example: 'He filled a bowl with cereal and milk.',
    translations: { en: 'Bowl', fr: 'Bol', es: 'Cuenco', ja: 'ボウル (booru)', hi: 'कटोरा (katora)', mr: 'वाटी (vaati)', ar: 'وعاء (wi\'a\')' },
    color: '#ff9800',
  },
  banana: {
    word: 'Banana', phonetic: '/bəˈnɑː.nə/', pos: 'noun',
    definition: 'A long curved fruit with a yellow skin and soft flesh.',
    example: 'He peeled the banana and ate it quickly.',
    translations: { en: 'Banana', fr: 'Banane', es: 'Plátano', ja: 'バナナ (banana)', hi: 'केला (kela)', mr: 'केळ (kel)', ar: 'موزة (mawza)' },
    color: '#ffeb3b',
  },
  apple: {
    word: 'Apple', phonetic: '/ˈæp.əl/', pos: 'noun',
    definition: 'A round fruit with red or green skin and white flesh.',
    example: 'She ate an apple as a healthy snack.',
    translations: { en: 'Apple', fr: 'Pomme', es: 'Manzana', ja: 'りんご (ringo)', hi: 'सेब (seb)', mr: 'सफरचंद (safarchand)', ar: 'تفاحة (tuffaha)' },
    color: '#f44336',
  },
  sandwich: {
    word: 'Sandwich', phonetic: '/ˈsæn.wɪdʒ/', pos: 'noun',
    definition: 'Two slices of bread with a filling between them.',
    example: 'She made a sandwich with cheese and tomato.',
    translations: { en: 'Sandwich', fr: 'Sandwich', es: 'Sándwich', ja: 'サンドイッチ (sandoitchi)', hi: 'सैंडविच (sandwich)', mr: 'सँडविच (sandwich)', ar: 'شطيرة (shatira)' },
    color: '#ff9800',
  },
  orange: {
    word: 'Orange', phonetic: '/ˈɒr.ɪndʒ/', pos: 'noun',
    definition: 'A round citrus fruit with orange skin and sweet juicy flesh.',
    example: 'He squeezed fresh oranges for juice.',
    translations: { en: 'Orange', fr: 'Orange', es: 'Naranja', ja: 'オレンジ (orenji)', hi: 'संतरा (santra)', mr: 'संत्रा (santra)', ar: 'برتقالة (burtuqala)' },
    color: '#ff9800',
  },
  broccoli: {
    word: 'Broccoli', phonetic: '/ˈbrɒk.ə.li/', pos: 'noun',
    definition: 'A green vegetable with tightly packed flower clusters.',
    example: 'She steamed broccoli as a side dish.',
    translations: { en: 'Broccoli', fr: 'Brocoli', es: 'Brócoli', ja: 'ブロッコリー (burokkorii)', hi: 'ब्रोकली (brokli)', mr: 'ब्रोकोली (brokoli)', ar: 'بروكلي (brukuli)' },
    color: '#4caf50',
  },
  carrot: {
    word: 'Carrot', phonetic: '/ˈkær.ət/', pos: 'noun',
    definition: 'A long orange root vegetable.',
    example: 'Rabbits love to eat carrots.',
    translations: { en: 'Carrot', fr: 'Carotte', es: 'Zanahoria', ja: 'にんじん (ninjin)', hi: 'गाजर (gajar)', mr: 'गाजर (gajar)', ar: 'جزرة (jazara)' },
    color: '#ff9800',
  },
  'hot dog': {
    word: 'Hot Dog', phonetic: '/hɒt dɒɡ/', pos: 'noun',
    definition: 'A cooked sausage served in a sliced bun.',
    example: 'He ate a hot dog at the baseball game.',
    translations: { en: 'Hot Dog', fr: 'Hot-dog', es: 'Perrito caliente', ja: 'ホットドッグ (hottodoggu)', hi: 'हॉट डॉग (hot dog)', mr: 'हॉट डॉग (hot dog)', ar: 'هوت دوغ (hot dog)' },
    color: '#ff5722',
  },
  pizza: {
    word: 'Pizza', phonetic: '/ˈpiːt.sə/', pos: 'noun',
    definition: 'A flat round bread topped with tomato sauce, cheese, and toppings.',
    example: 'They ordered a pizza with extra cheese.',
    translations: { en: 'Pizza', fr: 'Pizza', es: 'Pizza', ja: 'ピザ (piza)', hi: 'पिज़्ज़ा (pizza)', mr: 'पिझ्झा (pizza)', ar: 'بيتزا (bitsa)' },
    color: '#ff5722',
  },
  donut: {
    word: 'Donut', phonetic: '/ˈdəʊ.nʌt/', pos: 'noun',
    definition: 'A small fried cake, typically ring-shaped or filled.',
    example: 'She chose a chocolate donut from the bakery.',
    translations: { en: 'Donut', fr: 'Beignet', es: 'Rosquilla', ja: 'ドーナツ (doonatsu)', hi: 'डोनट (donut)', mr: 'डोनट (donut)', ar: 'دونات (donut)' },
    color: '#ff9800',
  },
  cake: {
    word: 'Cake', phonetic: '/keɪk/', pos: 'noun',
    definition: 'A sweet baked food made with flour, eggs, and sugar.',
    example: 'They sang "Happy Birthday" and cut the cake.',
    translations: { en: 'Cake', fr: 'Gâteau', es: 'Pastel', ja: 'ケーキ (keeki)', hi: 'केक (kek)', mr: 'केक (kek)', ar: 'كعكة (ka\'ka)' },
    color: '#e91e8c',
  },
  chair: {
    word: 'Chair', phonetic: '/tʃeər/', pos: 'noun',
    definition: 'A separate seat for one person, with a back.',
    example: 'She sat down on the chair and opened her book.',
    translations: { en: 'Chair', fr: 'Chaise', es: 'Silla', ja: '椅子 (isu)', hi: 'कुर्सी (kursi)', mr: 'खुर्ची (khurchi)', ar: 'كرسي (kursi)' },
    color: '#795548',
  },
  couch: {
    word: 'Couch', phonetic: '/kaʊtʃ/', pos: 'noun',
    definition: 'A long upholstered piece of furniture for sitting or lying on.',
    example: 'The family watched TV from the couch.',
    translations: { en: 'Couch', fr: 'Canapé', es: 'Sofá', ja: 'ソファ (sofa)', hi: 'सोफ़ा (sofa)', mr: 'सोफा (sofa)', ar: 'أريكة (arika)' },
    color: '#607d8b',
  },
  'potted plant': {
    word: 'Plant', phonetic: '/plɑːnt/', pos: 'noun',
    definition: 'A living organism that grows in soil, often kept indoors for decoration.',
    example: 'She watered the potted plant on the windowsill.',
    translations: { en: 'Plant', fr: 'Plante', es: 'Planta', ja: '植物 (shokubutsu)', hi: 'पौधा (paudha)', mr: 'कुंडीतील रोप (kundi rop)', ar: 'نبات (nabat)' },
    color: '#4caf50',
  },
  bed: {
    word: 'Bed', phonetic: '/bed/', pos: 'noun',
    definition: 'A piece of furniture for sleeping on.',
    example: 'He fell asleep as soon as he got into bed.',
    translations: { en: 'Bed', fr: 'Lit', es: 'Cama', ja: 'ベッド (beddo)', hi: 'बिस्तर (bistar)', mr: 'पलंग (palang)', ar: 'سرير (sarir)' },
    color: '#3f51b5',
  },
  'dining table': {
    word: 'Table', phonetic: '/ˈteɪ.bəl/', pos: 'noun',
    definition: 'A flat-topped piece of furniture with legs, used for eating.',
    example: 'The family gathered around the dining table.',
    translations: { en: 'Table', fr: 'Table', es: 'Mesa', ja: 'テーブル (teburu)', hi: 'मेज़ (mez)', mr: 'जेवणाचे टेबल (jevanche table)', ar: 'طاولة (tawila)' },
    color: '#795548',
  },
  toilet: {
    word: 'Toilet', phonetic: '/ˈtɔɪ.lət/', pos: 'noun',
    definition: 'A bowl-shaped fixture used for disposing of bodily waste.',
    example: 'He flushed the toilet after use.',
    translations: { en: 'Toilet', fr: 'Toilette', es: 'Inodoro', ja: 'トイレ (toire)', hi: 'शौचालय (shauchalay)', mr: 'शौचालय (shauchalay)', ar: 'مرحاض (mirhhad)' },
    color: '#9e9e9e',
  },
  tv: {
    word: 'Television', phonetic: '/ˈtel.ɪ.vɪʒ.ən/', pos: 'noun',
    definition: 'An electronic device for watching video and television programs.',
    example: 'They watched the news on television.',
    translations: { en: 'Television', fr: 'Télévision', es: 'Televisión', ja: 'テレビ (terebi)', hi: 'टेलीविज़न (television)', mr: 'दूरदर्शन (doordarshan)', ar: 'تلفاز (tilfaz)' },
    color: '#212121',
  },
  laptop: {
    word: 'Laptop', phonetic: '/ˈlæp.tɒp/', pos: 'noun',
    definition: 'A portable computer small enough to use on your lap.',
    example: 'She worked on her laptop at the café.',
    translations: { en: 'Laptop', fr: 'Ordinateur portable', es: 'Portátil', ja: 'ノートパソコン (nooto-pasonkon)', hi: 'लैपटॉप (laptop)', mr: 'लॅपटॉप (laptop)', ar: 'حاسوب محمول (hasoob mahmool)' },
    color: '#607d8b',
  },
  mouse: {
    word: 'Mouse', phonetic: '/maʊs/', pos: 'noun',
    definition: 'A small device moved by hand to control a computer cursor.',
    example: 'He clicked the mouse to open the file.',
    translations: { en: 'Mouse', fr: 'Souris', es: 'Ratón', ja: 'マウス (mausu)', hi: 'माउस (mouse)', mr: 'माउस (mouse)', ar: 'فأرة الحاسوب (fa\'arat hasoob)' },
    color: '#9e9e9e',
  },
  remote: {
    word: 'Remote', phonetic: '/rɪˈməʊt/', pos: 'noun',
    definition: 'A handheld device for operating a television from a distance.',
    example: 'She changed the channel with the remote.',
    translations: { en: 'Remote', fr: 'Télécommande', es: 'Control remoto', ja: 'リモコン (rimokon)', hi: 'रिमोट (remote)', mr: 'रिमोट (remote)', ar: 'جهاز تحكم (jihaz tahkum)' },
    color: '#212121',
  },
  keyboard: {
    word: 'Keyboard', phonetic: '/ˈkiː.bɔːrd/', pos: 'noun',
    definition: 'A set of keys used to operate a computer.',
    example: 'He typed the report on his keyboard.',
    translations: { en: 'Keyboard', fr: 'Clavier', es: 'Teclado', ja: 'キーボード (kiiboodo)', hi: 'कीबोर्ड (keyboard)', mr: 'कीबोर्ड (keyboard)', ar: 'لوحة مفاتيح (lawhat mafatih)' },
    color: '#607d8b',
  },
  'cell phone': {
    word: 'Phone', phonetic: '/fəʊn/', pos: 'noun',
    definition: 'A wireless handheld device used for calls and internet access.',
    example: 'She checked her messages on her cell phone.',
    translations: { en: 'Phone', fr: 'Téléphone', es: 'Teléfono', ja: '電話 (denwa)', hi: 'मोबाइल (mobile)', mr: 'मोबाईल (mobile)', ar: 'هاتف محمول (hatif mahmool)' },
    color: '#212121',
  },
  microwave: {
    word: 'Microwave', phonetic: '/ˈmaɪ.krə.weɪv/', pos: 'noun',
    definition: 'An electric oven that heats food using microwave radiation.',
    example: 'She heated her soup in the microwave.',
    translations: { en: 'Microwave', fr: 'Micro-ondes', es: 'Microondas', ja: '電子レンジ (denshi-renji)', hi: 'माइक्रोवेव (microwave)', mr: 'मायक्रोवेव्ह (microwave)', ar: 'ميكروويف (microwave)' },
    color: '#9e9e9e',
  },
  oven: {
    word: 'Oven', phonetic: '/ˈʌv.ən/', pos: 'noun',
    definition: 'A kitchen appliance used for baking and roasting food.',
    example: 'She preheated the oven before baking cookies.',
    translations: { en: 'Oven', fr: 'Four', es: 'Horno', ja: 'オーブン (oobun)', hi: 'ओवन (oven)', mr: 'ओव्हन (oven)', ar: 'فرن (furn)' },
    color: '#9e9e9e',
  },
  sink: {
    word: 'Sink', phonetic: '/sɪŋk/', pos: 'noun',
    definition: 'A basin with taps for washing hands or dishes.',
    example: 'He washed the dishes in the sink.',
    translations: { en: 'Sink', fr: 'Évier', es: 'Fregadero', ja: 'シンク (shinku)', hi: 'नल (nal)', mr: 'ओटा (ota)', ar: 'حوض (hawd)' },
    color: '#9e9e9e',
  },
  refrigerator: {
    word: 'Refrigerator', phonetic: '/rɪˈfrɪdʒ.ər.eɪ.tər/', pos: 'noun',
    definition: 'An appliance that keeps food and drinks cold.',
    example: 'She put the leftovers in the refrigerator.',
    translations: { en: 'Refrigerator', fr: 'Réfrigérateur', es: 'Nevera', ja: '冷蔵庫 (reizouko)', hi: 'फ्रिज (fridge)', mr: 'फ्रिज (fridge)', ar: 'ثلاجة (thallaja)' },
    color: '#9e9e9e',
  },
  book: {
    word: 'Book', phonetic: '/bʊk/', pos: 'noun',
    definition: 'A written or printed work consisting of pages bound together.',
    example: 'She read a book every week.',
    translations: { en: 'Book', fr: 'Livre', es: 'Libro', ja: '本 (hon)', hi: 'किताब (kitaab)', mr: 'पुस्तक (pustak)', ar: 'كتاب (kitaab)' },
    color: '#3f51b5',
  },
  clock: {
    word: 'Clock', phonetic: '/klɒk/', pos: 'noun',
    definition: 'A device that measures and shows the time.',
    example: 'The clock on the wall showed it was noon.',
    translations: { en: 'Clock', fr: 'Horloge', es: 'Reloj', ja: '時計 (tokei)', hi: 'घड़ी (ghadi)', mr: 'घड्याळ (ghadyal)', ar: 'ساعة (sa\'a)' },
    color: '#f44336',
  },
  vase: {
    word: 'Vase', phonetic: '/vɑːz/', pos: 'noun',
    definition: 'A decorative container used to hold flowers.',
    example: 'She placed fresh flowers in the vase.',
    translations: { en: 'Vase', fr: 'Vase', es: 'Jarrón', ja: '花瓶 (kabin)', hi: 'फूलदान (phuldan)', mr: 'फुलदाणी (phuldaani)', ar: 'مزهرية (mazhariyya)' },
    color: '#9c27b0',
  },
  scissors: {
    word: 'Scissors', phonetic: '/ˈsɪz.əz/', pos: 'noun',
    definition: 'A cutting tool with two crossed blades.',
    example: 'She used scissors to cut the paper.',
    translations: { en: 'Scissors', fr: 'Ciseaux', es: 'Tijeras', ja: 'はさみ (hasami)', hi: 'कैंची (kaichi)', mr: 'कात्री (kaatri)', ar: 'مقص (miqass)' },
    color: '#9e9e9e',
  },
  'teddy bear': {
    word: 'Teddy Bear', phonetic: '/ˈted.i beər/', pos: 'noun',
    definition: 'A soft toy stuffed bear, popular with children.',
    example: 'The child hugged her teddy bear to sleep.',
    translations: { en: 'Teddy Bear', fr: 'Nounours', es: 'Osito de peluche', ja: 'テディベア (tediibea)', hi: 'टेडी बेयर (teddy bear)', mr: 'टेडी बेअर (teddy bear)', ar: 'دمية دب (dumyat dubb)' },
    color: '#795548',
  },
  toothbrush: {
    word: 'Toothbrush', phonetic: '/ˈtuːθ.brʌʃ/', pos: 'noun',
    definition: 'A small brush for cleaning teeth.',
    example: 'He brushed his teeth with a toothbrush.',
    translations: { en: 'Toothbrush', fr: 'Brosse à dents', es: 'Cepillo de dientes', ja: '歯ブラシ (haburashi)', hi: 'टूथब्रश (toothbrush)', mr: 'दात घासण्याचा ब्रश (daat brush)', ar: 'فرشاة أسنان (furshaat asnan)' },
    color: '#2196f3',
  },
  'sports ball': {
    word: 'Ball', phonetic: '/bɔːl/', pos: 'noun',
    definition: 'A round object used in sports and games.',
    example: 'He kicked the ball into the goal.',
    translations: { en: 'Ball', fr: 'Ballon', es: 'Pelota', ja: 'ボール (booru)', hi: 'गेंद (gend)', mr: 'चेंडू (chendu)', ar: 'كرة (kura)' },
    color: '#ff5722',
  },
  'tennis racket': {
    word: 'Racket', phonetic: '/ˈræk.ɪt/', pos: 'noun',
    definition: 'A bat with a round frame strung with cord, used in tennis.',
    example: 'She swung the tennis racket and hit the ball.',
    translations: { en: 'Racket', fr: 'Raquette', es: 'Raqueta', ja: 'ラケット (raketto)', hi: 'रैकेट (racket)', mr: 'रॅकेट (racket)', ar: 'مضرب تنس (madrab tinis)' },
    color: '#4caf50',
  },
  skateboard: {
    word: 'Skateboard', phonetic: '/ˈskeɪt.bɔːrd/', pos: 'noun',
    definition: 'A narrow board with wheels used for riding.',
    example: 'He performed tricks on his skateboard.',
    translations: { en: 'Skateboard', fr: 'Skateboard', es: 'Monopatín', ja: 'スケートボード (sukeeto boodo)', hi: 'स्केटबोर्ड (skateboard)', mr: 'स्केटबोर्ड (skateboard)', ar: 'لوح تزلج (lawh tazalluj)' },
    color: '#ff9800',
  },
  kite: {
    word: 'Kite', phonetic: '/kaɪt/', pos: 'noun',
    definition: 'A light frame covered with fabric, flown in the wind on a string.',
    example: 'The children flew a kite on a windy day.',
    translations: { en: 'Kite', fr: 'Cerf-volant', es: 'Cometa', ja: '凧 (tako)', hi: 'पतंग (patang)', mr: 'पतंग (patang)', ar: 'طائرة ورقية (ta\'ira waraqiyya)' },
    color: '#e91e8c',
  },
  'traffic light': {
    word: 'Traffic Light', phonetic: '/ˈtræf.ɪk laɪt/', pos: 'noun',
    definition: 'A signaling device with red, yellow, and green lights controlling traffic.',
    example: 'She waited for the traffic light to turn green.',
    translations: { en: 'Traffic Light', fr: 'Feu de circulation', es: 'Semáforo', ja: '信号機 (shingouki)', hi: 'ट्रैफ़िक लाइट (traffic light)', mr: 'वाहतूक दिवा (vahatuk diva)', ar: 'إشارة مرور (ishaarat muroor)' },
    color: '#4caf50',
  },
  'fire hydrant': {
    word: 'Fire Hydrant', phonetic: '/faɪər ˈhaɪ.drənt/', pos: 'noun',
    definition: 'A device in the street connected to water pipes for firefighting.',
    example: 'The firefighter connected the hose to the fire hydrant.',
    translations: { en: 'Fire Hydrant', fr: "Bouche d'incendie", es: 'Hidrante', ja: '消火栓 (shokasen)', hi: 'फ़ायर हाइड्रेंट (fire hydrant)', mr: 'अग्निशामक नळ (agnishamak nal)', ar: 'صنبور الحريق (sanboor al-hariq)' },
    color: '#f44336',
  },
  'stop sign': {
    word: 'Stop Sign', phonetic: '/stɒp saɪn/', pos: 'noun',
    definition: 'A red octagonal road sign instructing drivers to stop.',
    example: 'He stopped his car at the stop sign.',
    translations: { en: 'Stop Sign', fr: 'Panneau stop', es: 'Señal de stop', ja: '一時停止 (ichiji teishi)', hi: 'रुकने का संकेत (stop sign)', mr: 'थांबा (thaamba)', ar: 'علامة قف (\'alamat qif)' },
    color: '#f44336',
  },
};

// Fallback for COCO labels not in the main database
const COCO_FALLBACKS = {
  airplane:        { word: 'Airplane',       translations: { en: 'Airplane',       fr: 'Avion',           es: 'Avión',          ja: '飛行機 (hikouki)',          hi: 'हवाई जहाज़ (hawai jahaz)',  mr: 'विमान (viman)',          ar: 'طائرة (ta\'ira)' } },
  train:           { word: 'Train',          translations: { en: 'Train',          fr: 'Train',           es: 'Tren',           ja: '電車 (densha)',            hi: 'ट्रेन (train)',           mr: 'रेल्वे (railway)',        ar: 'قطار (qitar)' } },
  boat:            { word: 'Boat',           translations: { en: 'Boat',           fr: 'Bateau',          es: 'Barco',          ja: 'ボート (booto)',           hi: 'नाव (naav)',             mr: 'होडी (hodi)',            ar: 'قارب (qarib)' } },
  'parking meter': { word: 'Parking Meter', translations: { en: 'Parking Meter',  fr: 'Parcomètre',      es: 'Parquímetro',    ja: 'パーキングメーター',        hi: 'पार्किंग मीटर',          mr: 'पार्किंग मीटर',          ar: 'عداد الوقوف (\'addad al-wuquf)' } },
  frisbee:         { word: 'Frisbee',        translations: { en: 'Frisbee',        fr: 'Frisbee',         es: 'Frisbee',        ja: 'フリスビー (furisubii)',    hi: 'फ्रिसबी (frisbee)',       mr: 'फ्रिस्बी (frisbee)',      ar: 'فريسبي (frisbee)' } },
  skis:            { word: 'Skis',           translations: { en: 'Skis',           fr: 'Skis',            es: 'Esquís',         ja: 'スキー (sukii)',           hi: 'स्की (ski)',             mr: 'स्की (ski)',             ar: 'تزلج (tazalluj)' } },
  snowboard:       { word: 'Snowboard',      translations: { en: 'Snowboard',      fr: 'Snowboard',       es: 'Snowboard',      ja: 'スノーボード (sunooboodo)', hi: 'स्नोबोर्ड (snowboard)',   mr: 'स्नोबोर्ड (snowboard)',   ar: 'لوح الثلج (lawh al-thalj)' } },
  'baseball bat':  { word: 'Baseball Bat',  translations: { en: 'Baseball Bat',   fr: 'Batte de baseball', es: 'Bate',         ja: 'バット (batto)',           hi: 'बैट (bat)',              mr: 'बॅट (bat)',              ar: 'مضرب بيسبول (madrab baseball)' } },
  'baseball glove':{ word: 'Baseball Glove',translations: { en: 'Baseball Glove', fr: 'Gant de baseball', es: 'Guante',        ja: 'グローブ (guroobu)',       hi: 'ग्लव (glove)',           mr: 'ग्लोव्ह (glove)',        ar: 'قفاز البيسبول (quffaz baseball)' } },
  surfboard:       { word: 'Surfboard',      translations: { en: 'Surfboard',      fr: 'Planche de surf', es: 'Tabla de surf',  ja: 'サーフボード (saafu boodo)', hi: 'सर्फ़बोर्ड (surfboard)',  mr: 'सर्फबोर्ड (surfboard)',   ar: 'لوح التزلج (lawh al-tazalluj)' } },
  tie:             { word: 'Tie',            translations: { en: 'Tie',            fr: 'Cravate',         es: 'Corbata',        ja: 'ネクタイ (nekutai)',       hi: 'टाई (tie)',             mr: 'टाय (tie)',             ar: 'ربطة عنق (ribtat \'unuq)' } },
  'hair drier':    { word: 'Hair Dryer',     translations: { en: 'Hair Dryer',     fr: 'Sèche-cheveux',   es: 'Secador',        ja: 'ドライヤー (doraiyaa)',    hi: 'हेयर ड्रायर (hair dryer)', mr: 'हेअर ड्रायर (hair dryer)', ar: 'مجفف الشعر (mujaffif al-sha\'r)' } },
  toaster:         { word: 'Toaster',        translations: { en: 'Toaster',        fr: 'Grille-pain',     es: 'Tostadora',      ja: 'トースター (toosutaa)',    hi: 'टोस्टर (toaster)',       mr: 'टोस्टर (toaster)',       ar: 'محمصة (mahmassa)' } },
};

// ─── Extended Dictionary (MobileNet / ImageNet classes) ─────────────────────
// Covers musical instruments, clothing, tools, food, nature, animals, buildings, etc.

const EXTENDED_VOCABULARY = {
  // ── Musical Instruments ──────────────────────────────────────────────────
  guitar: {
    word: 'Guitar', phonetic: '/ɡɪˈtɑːr/', pos: 'noun',
    definition: 'A stringed musical instrument played by plucking or strumming.',
    example: 'He played a beautiful melody on the guitar.',
    translations: { en: 'Guitar', fr: 'Guitare', es: 'Guitarra', ja: 'ギター (gitaa)', hi: 'गिटार (guitar)', mr: 'गिटार (guitar)', ar: 'قيثارة (qithara)' },
    color: '#795548',
  },
  'acoustic guitar': {
    word: 'Guitar', phonetic: '/ɡɪˈtɑːr/', pos: 'noun',
    definition: 'A stringed musical instrument played by plucking or strumming.',
    example: 'She strummed her acoustic guitar by the campfire.',
    translations: { en: 'Guitar', fr: 'Guitare', es: 'Guitarra', ja: 'ギター (gitaa)', hi: 'गिटार (guitar)', mr: 'गिटार (guitar)', ar: 'قيثارة (qithara)' },
    color: '#795548',
  },
  'electric guitar': {
    word: 'Electric Guitar', phonetic: '/ɪˈlek.trɪk ɡɪˈtɑːr/', pos: 'noun',
    definition: 'A guitar that uses electronic pickups to amplify its sound.',
    example: 'The rock band played an electric guitar solo.',
    translations: { en: 'Electric Guitar', fr: 'Guitare électrique', es: 'Guitarra eléctrica', ja: 'エレキギター (ereki gitaa)', hi: 'इलेक्ट्रिक गिटार', mr: 'इलेक्ट्रिक गिटार', ar: 'غيتار كهربائي (ghitar kahruba\'i)' },
    color: '#f44336',
  },
  violin: {
    word: 'Violin', phonetic: '/ˌvaɪ.əˈlɪn/', pos: 'noun',
    definition: 'A small four-stringed instrument played with a bow.',
    example: 'The violinist performed a solo at the concert.',
    translations: { en: 'Violin', fr: 'Violon', es: 'Violín', ja: 'バイオリン (baiorin)', hi: 'वायलिन (violin)', mr: 'व्हायोलिन (violin)', ar: 'كمان (kaman)' },
    color: '#795548',
  },
  piano: {
    word: 'Piano', phonetic: '/piˈæn.əʊ/', pos: 'noun',
    definition: 'A large keyboard instrument producing sound by striking strings with hammers.',
    example: 'She practiced the piano for two hours every day.',
    translations: { en: 'Piano', fr: 'Piano', es: 'Piano', ja: 'ピアノ (piano)', hi: 'पियानो (piano)', mr: 'पियानो (piano)', ar: 'بيانو (biano)' },
    color: '#212121',
  },
  'grand piano': {
    word: 'Piano', phonetic: '/piˈæn.əʊ/', pos: 'noun',
    definition: 'A large keyboard instrument producing sound by striking strings with hammers.',
    example: 'The grand piano dominated the concert hall.',
    translations: { en: 'Piano', fr: 'Piano', es: 'Piano', ja: 'ピアノ (piano)', hi: 'पियानो (piano)', mr: 'पियानो (piano)', ar: 'بيانو (biano)' },
    color: '#212121',
  },
  drum: {
    word: 'Drum', phonetic: '/drʌm/', pos: 'noun',
    definition: 'A percussion instrument played by hitting with sticks or hands.',
    example: 'The drummer kept a steady beat throughout the song.',
    translations: { en: 'Drum', fr: 'Tambour', es: 'Tambor', ja: 'ドラム (doramu)', hi: 'ढोल (dhol)', mr: 'ढोल (dhol)', ar: 'طبل (tabl)' },
    color: '#ff5722',
  },
  saxophone: {
    word: 'Saxophone', phonetic: '/ˈsæk.sə.fəʊn/', pos: 'noun',
    definition: 'A wind instrument with a reed mouthpiece and a conical metal body.',
    example: 'He played the saxophone in the jazz band.',
    translations: { en: 'Saxophone', fr: 'Saxophone', es: 'Saxofón', ja: 'サックス (sakkusu)', hi: 'सैक्सोफोन (saxophone)', mr: 'सॅक्सोफोन (saxophone)', ar: 'ساكسفون (saxophone)' },
    color: '#ff9800',
  },
  trumpet: {
    word: 'Trumpet', phonetic: '/ˈtrʌm.pɪt/', pos: 'noun',
    definition: 'A brass wind instrument with a flared bell and valves.',
    example: 'The trumpet player hit a high note perfectly.',
    translations: { en: 'Trumpet', fr: 'Trompette', es: 'Trompeta', ja: 'トランペット (torampetto)', hi: 'तुरही (turahi)', mr: 'तुतारी (tutari)', ar: 'بوق (buq)' },
    color: '#ff9800',
  },
  flute: {
    word: 'Flute', phonetic: '/fluːt/', pos: 'noun',
    definition: 'A thin, tubular wind instrument played by blowing across a hole.',
    example: 'She played a soft melody on the flute.',
    translations: { en: 'Flute', fr: 'Flûte', es: 'Flauta', ja: 'フルート (furuuto)', hi: 'बांसुरी (bansuri)', mr: 'बासरी (basari)', ar: 'ناي (nay)' },
    color: '#9e9e9e',
  },
  accordion: {
    word: 'Accordion', phonetic: '/əˈkɔː.di.ən/', pos: 'noun',
    definition: 'A box-shaped musical instrument with bellows and keys.',
    example: 'He played the accordion at the folk festival.',
    translations: { en: 'Accordion', fr: 'Accordéon', es: 'Acordeón', ja: 'アコーディオン (akoodion)', hi: 'अकॉर्डियन (accordion)', mr: 'अकॉर्डियन (accordion)', ar: 'أكورديون (accordion)' },
    color: '#e91e8c',
  },
  harmonica: {
    word: 'Harmonica', phonetic: '/hɑːrˈmɒn.ɪ.kə/', pos: 'noun',
    definition: 'A small wind instrument played by blowing and drawing air through holes.',
    example: 'He pulled out a harmonica and began to play.',
    translations: { en: 'Harmonica', fr: 'Harmonica', es: 'Armónica', ja: 'ハーモニカ (haamonika)', hi: 'हारमोनिका (harmonica)', mr: 'हार्मोनिका (harmonica)', ar: 'هارمونيكا (harmonica)' },
    color: '#9e9e9e',
  },
  harp: {
    word: 'Harp', phonetic: '/hɑːrp/', pos: 'noun',
    definition: 'A large stringed instrument with strings stretched on a frame.',
    example: 'The harpist plucked the strings gently.',
    translations: { en: 'Harp', fr: 'Harpe', es: 'Arpa', ja: 'ハープ (haapu)', hi: 'वीणा (veena)', mr: 'वीणा (veena)', ar: 'قيثار (qithar)' },
    color: '#ff9800',
  },
  cello: {
    word: 'Cello', phonetic: '/ˈtʃel.əʊ/', pos: 'noun',
    definition: 'A large stringed instrument played with a bow, held between the knees.',
    example: 'The cello added depth to the orchestra.',
    translations: { en: 'Cello', fr: 'Violoncelle', es: 'Violonchelo', ja: 'チェロ (chero)', hi: 'चेलो (cello)', mr: 'चेलो (cello)', ar: 'تشيللو (cello)' },
    color: '#795548',
  },
  banjo: {
    word: 'Banjo', phonetic: '/ˈbæn.dʒəʊ/', pos: 'noun',
    definition: 'A stringed instrument with a round body and long neck.',
    example: 'He played the banjo at the bluegrass festival.',
    translations: { en: 'Banjo', fr: 'Banjo', es: 'Banjo', ja: 'バンジョー (banjoo)', hi: 'बांजो (banjo)', mr: 'बँजो (banjo)', ar: 'بانجو (banjo)' },
    color: '#ff9800',
  },
  microphone: {
    word: 'Microphone', phonetic: '/ˈmaɪ.krə.fəʊn/', pos: 'noun',
    definition: 'A device that converts sound into an electrical signal for recording or amplifying.',
    example: 'The singer leaned into the microphone.',
    translations: { en: 'Microphone', fr: 'Microphone', es: 'Micrófono', ja: 'マイク (maiku)', hi: 'माइक्रोफोन (microphone)', mr: 'माइक (mike)', ar: 'ميكروفون (microphone)' },
    color: '#212121',
  },
  headphones: {
    word: 'Headphones', phonetic: '/ˈhed.fəʊnz/', pos: 'noun',
    definition: 'A pair of speakers worn over the ears for listening to audio.',
    example: 'She put on her headphones and started listening to music.',
    translations: { en: 'Headphones', fr: 'Casque', es: 'Auriculares', ja: 'ヘッドフォン (heddofon)', hi: 'हेडफोन (headphone)', mr: 'हेडफोन (headphone)', ar: 'سماعات (sama\'at)' },
    color: '#212121',
  },

  // ── Clothing & Accessories ───────────────────────────────────────────────
  shirt: {
    word: 'Shirt', phonetic: '/ʃɜːrt/', pos: 'noun',
    definition: 'A garment for the upper body with a collar and buttons.',
    example: 'He wore a white shirt to the interview.',
    translations: { en: 'Shirt', fr: 'Chemise', es: 'Camisa', ja: 'シャツ (shatsu)', hi: 'कमीज़ (kameez)', mr: 'शर्ट (shirt)', ar: 'قميص (qamis)' },
    color: '#2196f3',
  },
  dress: {
    word: 'Dress', phonetic: '/dres/', pos: 'noun',
    definition: 'A one-piece garment covering the body and extending to the legs.',
    example: 'She wore a red dress to the party.',
    translations: { en: 'Dress', fr: 'Robe', es: 'Vestido', ja: 'ドレス (doresu)', hi: 'पोशाक (poshak)', mr: 'ड्रेस (dress)', ar: 'فستان (fustan)' },
    color: '#e91e8c',
  },
  shoe: {
    word: 'Shoe', phonetic: '/ʃuː/', pos: 'noun',
    definition: 'A covering for the foot, typically with a sole and upper.',
    example: 'She bought a new pair of shoes.',
    translations: { en: 'Shoe', fr: 'Chaussure', es: 'Zapato', ja: '靴 (kutsu)', hi: 'जूता (joota)', mr: 'बूट (boot)', ar: 'حذاء (hidaa)' },
    color: '#795548',
  },
  boot: {
    word: 'Boot', phonetic: '/buːt/', pos: 'noun',
    definition: 'A sturdy shoe that covers the ankle and lower leg.',
    example: 'He wore hiking boots on the mountain trail.',
    translations: { en: 'Boot', fr: 'Botte', es: 'Bota', ja: 'ブーツ (buutsu)', hi: 'बूट (boot)', mr: 'बूट (boot)', ar: 'حذاء طويل (hidaa tawil)' },
    color: '#795548',
  },
  hat: {
    word: 'Hat', phonetic: '/hæt/', pos: 'noun',
    definition: 'A shaped covering for the head.',
    example: 'She put on a sun hat before going outside.',
    translations: { en: 'Hat', fr: 'Chapeau', es: 'Sombrero', ja: '帽子 (boushi)', hi: 'टोपी (topi)', mr: 'टोपी (topi)', ar: 'قبعة (qub\'a)' },
    color: '#ff9800',
  },
  sunglasses: {
    word: 'Sunglasses', phonetic: '/ˈsʌnˌɡlɑː.sɪz/', pos: 'noun',
    definition: 'Tinted glasses worn to protect the eyes from sunlight.',
    example: 'He put on his sunglasses before stepping outside.',
    translations: { en: 'Sunglasses', fr: 'Lunettes de soleil', es: 'Gafas de sol', ja: 'サングラス (sangurasu)', hi: 'धूप का चश्मा (dhoop ka chashma)', mr: 'गॉगल (gogal)', ar: 'نظارات شمسية (nazzarat shamsiyya)' },
    color: '#212121',
  },
  scarf: {
    word: 'Scarf', phonetic: '/skɑːrf/', pos: 'noun',
    definition: 'A length of fabric worn around the neck for warmth or style.',
    example: 'She wrapped a scarf around her neck in the cold.',
    translations: { en: 'Scarf', fr: 'Écharpe', es: 'Bufanda', ja: 'スカーフ (sukaafu)', hi: 'दुपट्टा (dupatta)', mr: 'स्कार्फ (scarf)', ar: 'وشاح (wisah)' },
    color: '#e91e8c',
  },
  glove: {
    word: 'Glove', phonetic: '/ɡlʌv/', pos: 'noun',
    definition: 'A covering for the hand with separate sections for each finger.',
    example: 'She wore gloves to keep her hands warm.',
    translations: { en: 'Glove', fr: 'Gant', es: 'Guante', ja: '手袋 (tebukuro)', hi: 'दस्ताना (dastana)', mr: 'हातमोजे (hatmoje)', ar: 'قفاز (quffaz)' },
    color: '#9e9e9e',
  },
  jacket: {
    word: 'Jacket', phonetic: '/ˈdʒæk.ɪt/', pos: 'noun',
    definition: 'A short coat with a front opening and sleeves.',
    example: 'He put on his leather jacket before leaving.',
    translations: { en: 'Jacket', fr: 'Veste', es: 'Chaqueta', ja: 'ジャケット (jaketto)', hi: 'जैकेट (jacket)', mr: 'जाकीट (jacket)', ar: 'سترة (sutra)' },
    color: '#607d8b',
  },
  sock: {
    word: 'Sock', phonetic: '/sɒk/', pos: 'noun',
    definition: 'A knitted garment worn on the foot inside a shoe.',
    example: 'He put on a pair of warm socks.',
    translations: { en: 'Sock', fr: 'Chaussette', es: 'Calcetín', ja: '靴下 (kutsushita)', hi: 'मोज़ा (moza)', mr: 'मोजा (moja)', ar: 'جورب (jurab)' },
    color: '#9e9e9e',
  },
  wallet: {
    word: 'Wallet', phonetic: '/ˈwɒl.ɪt/', pos: 'noun',
    definition: 'A small flat case for carrying money and cards.',
    example: 'He took money out of his wallet to pay.',
    translations: { en: 'Wallet', fr: 'Portefeuille', es: 'Billetera', ja: '財布 (saifu)', hi: 'बटुआ (batua)', mr: 'पाकीट (pakit)', ar: 'محفظة (mahfaza)' },
    color: '#795548',
  },

  // ── Tools & Hardware ────────────────────────────────────────────────────
  hammer: {
    word: 'Hammer', phonetic: '/ˈhæm.ər/', pos: 'noun',
    definition: 'A tool with a heavy head and a handle, used for hitting nails.',
    example: 'He used a hammer to hang the picture frame.',
    translations: { en: 'Hammer', fr: 'Marteau', es: 'Martillo', ja: 'ハンマー (hanmaa)', hi: 'हथौड़ा (hathauda)', mr: 'घण (ghan)', ar: 'مطرقة (matraqa)' },
    color: '#795548',
  },
  screwdriver: {
    word: 'Screwdriver', phonetic: '/ˈskruːˌdraɪ.vər/', pos: 'noun',
    definition: 'A tool for turning screws with a slotted or cross-shaped tip.',
    example: 'She used a screwdriver to tighten the loose screw.',
    translations: { en: 'Screwdriver', fr: 'Tournevis', es: 'Destornillador', ja: 'ドライバー (doraibaa)', hi: 'पेचकस (pechkas)', mr: 'स्क्रू ड्रायव्हर (screw driver)', ar: 'مفك براغي (mufakk baragi)' },
    color: '#9e9e9e',
  },
  wrench: {
    word: 'Wrench', phonetic: '/rentʃ/', pos: 'noun',
    definition: 'A tool used for gripping and turning nuts and bolts.',
    example: 'The mechanic used a wrench to fix the pipe.',
    translations: { en: 'Wrench', fr: 'Clé', es: 'Llave inglesa', ja: 'レンチ (renchi)', hi: 'रेंच (wrench)', mr: 'रेंच (wrench)', ar: 'مفتاح ربط (miftah rabt)' },
    color: '#9e9e9e',
  },
  broom: {
    word: 'Broom', phonetic: '/bruːm/', pos: 'noun',
    definition: 'A long-handled brush used for sweeping floors.',
    example: 'She swept the kitchen floor with a broom.',
    translations: { en: 'Broom', fr: 'Balai', es: 'Escoba', ja: 'ほうき (houki)', hi: 'झाड़ू (jhadu)', mr: 'झाडू (jhadu)', ar: 'مكنسة (miknasa)' },
    color: '#795548',
  },
  shovel: {
    word: 'Shovel', phonetic: '/ˈʃʌv.əl/', pos: 'noun',
    definition: 'A tool with a broad blade and long handle for digging.',
    example: 'He used a shovel to dig a hole in the garden.',
    translations: { en: 'Shovel', fr: 'Pelle', es: 'Pala', ja: 'シャベル (shaberu)', hi: 'फावड़ा (phawda)', mr: 'फावडे (phawde)', ar: 'مجرفة (mijrafa)' },
    color: '#795548',
  },
  bucket: {
    word: 'Bucket', phonetic: '/ˈbʌk.ɪt/', pos: 'noun',
    definition: 'A cylindrical open container with a handle, used for carrying liquids.',
    example: 'She filled a bucket with water to wash the car.',
    translations: { en: 'Bucket', fr: 'Seau', es: 'Cubo', ja: 'バケツ (baketsu)', hi: 'बाल्टी (balti)', mr: 'बादली (badali)', ar: 'دلو (dalw)' },
    color: '#ff9800',
  },
  ladder: {
    word: 'Ladder', phonetic: '/ˈlæd.ər/', pos: 'noun',
    definition: 'A structure of horizontal steps fixed between two upright poles for climbing.',
    example: 'He climbed the ladder to fix the roof.',
    translations: { en: 'Ladder', fr: 'Échelle', es: 'Escalera', ja: 'はしご (hashigo)', hi: 'सीढ़ी (seedhi)', mr: 'शिडी (shidi)', ar: 'سلم (sullam)' },
    color: '#ff9800',
  },
  saw: {
    word: 'Saw', phonetic: '/sɔː/', pos: 'noun',
    definition: 'A tool with a serrated blade used for cutting wood or metal.',
    example: 'He used a saw to cut the plank of wood.',
    translations: { en: 'Saw', fr: 'Scie', es: 'Sierra', ja: 'のこぎり (nokogiri)', hi: 'आरी (aari)', mr: 'करवत (karvat)', ar: 'منشار (minshar)' },
    color: '#9e9e9e',
  },
  paintbrush: {
    word: 'Paintbrush', phonetic: '/ˈpeɪnt.brʌʃ/', pos: 'noun',
    definition: 'A brush used for applying paint to surfaces.',
    example: 'She dipped the paintbrush into the red paint.',
    translations: { en: 'Paintbrush', fr: 'Pinceau', es: 'Pincel', ja: '絵筆 (efude)', hi: 'पेंट ब्रश (paint brush)', mr: 'पेंट ब्रश (paint brush)', ar: 'فرشاة رسم (furshaat rasm)' },
    color: '#e91e8c',
  },

  // ── Electronics & Gadgets ────────────────────────────────────────────────
  camera: {
    word: 'Camera', phonetic: '/ˈkæm.ər.ə/', pos: 'noun',
    definition: 'A device for capturing photographs or video.',
    example: 'She used a camera to photograph the sunset.',
    translations: { en: 'Camera', fr: 'Appareil photo', es: 'Cámara', ja: 'カメラ (kamera)', hi: 'कैमरा (camera)', mr: 'कॅमेरा (camera)', ar: 'كاميرا (kamera)' },
    color: '#212121',
  },
  watch: {
    word: 'Watch', phonetic: '/wɒtʃ/', pos: 'noun',
    definition: 'A small timepiece worn on the wrist.',
    example: 'He glanced at his watch to check the time.',
    translations: { en: 'Watch', fr: 'Montre', es: 'Reloj de pulsera', ja: '腕時計 (udedokei)', hi: 'घड़ी (ghadi)', mr: 'घड्याळ (ghadyal)', ar: 'ساعة يد (sa\'at yad)' },
    color: '#607d8b',
  },
  calculator: {
    word: 'Calculator', phonetic: '/ˈkæl.kjʊ.leɪ.tər/', pos: 'noun',
    definition: 'An electronic device for performing mathematical calculations.',
    example: 'She used a calculator to add up the total.',
    translations: { en: 'Calculator', fr: 'Calculatrice', es: 'Calculadora', ja: '電卓 (dentaku)', hi: 'कैलकुलेटर (calculator)', mr: 'कॅल्क्युलेटर (calculator)', ar: 'آلة حاسبة (ala hasiba)' },
    color: '#607d8b',
  },
  radio: {
    word: 'Radio', phonetic: '/ˈreɪ.di.əʊ/', pos: 'noun',
    definition: 'A device that receives and plays broadcast audio signals.',
    example: 'They listened to the news on the radio.',
    translations: { en: 'Radio', fr: 'Radio', es: 'Radio', ja: 'ラジオ (rajio)', hi: 'रेडियो (radio)', mr: 'रेडिओ (radio)', ar: 'راديو (radio)' },
    color: '#607d8b',
  },
  printer: {
    word: 'Printer', phonetic: '/ˈprɪn.tər/', pos: 'noun',
    definition: 'A machine that transfers text or images from a computer onto paper.',
    example: 'She sent the document to the printer.',
    translations: { en: 'Printer', fr: 'Imprimante', es: 'Impresora', ja: 'プリンター (purintaa)', hi: 'प्रिंटर (printer)', mr: 'प्रिंटर (printer)', ar: 'طابعة (tabi\'a)' },
    color: '#9e9e9e',
  },
  projector: {
    word: 'Projector', phonetic: '/prəˈdʒek.tər/', pos: 'noun',
    definition: 'A device that projects images or video onto a screen or surface.',
    example: 'The teacher used a projector to show the slides.',
    translations: { en: 'Projector', fr: 'Projecteur', es: 'Proyector', ja: 'プロジェクター (purojekutaa)', hi: 'प्रोजेक्टर (projector)', mr: 'प्रोजेक्टर (projector)', ar: 'جهاز عرض (jihaz \'ard)' },
    color: '#212121',
  },
  'power outlet': {
    word: 'Outlet', phonetic: '/ˈaʊt.lɪt/', pos: 'noun',
    definition: 'A socket in a wall where electrical devices can be plugged in.',
    example: 'He plugged the charger into the power outlet.',
    translations: { en: 'Outlet', fr: 'Prise électrique', es: 'Enchufe', ja: 'コンセント (konsento)', hi: 'बिजली का सॉकेट (socket)', mr: 'सॉकेट (socket)', ar: 'مقبس كهربائي (maqbas kahruba\'i)' },
    color: '#9e9e9e',
  },

  // ── Food & Drink ─────────────────────────────────────────────────────────
  coffee: {
    word: 'Coffee', phonetic: '/ˈkɒf.i/', pos: 'noun',
    definition: 'A hot drink made from roasted ground beans.',
    example: 'She started every morning with a cup of coffee.',
    translations: { en: 'Coffee', fr: 'Café', es: 'Café', ja: 'コーヒー (koohii)', hi: 'कॉफ़ी (coffee)', mr: 'कॉफी (coffee)', ar: 'قهوة (qahwa)' },
    color: '#795548',
  },
  espresso: {
    word: 'Espresso', phonetic: '/eˈspres.əʊ/', pos: 'noun',
    definition: 'A strong coffee made by forcing pressurized water through ground coffee.',
    example: 'He ordered a double espresso at the café.',
    translations: { en: 'Espresso', fr: 'Expresso', es: 'Espresso', ja: 'エスプレッソ (esupuresso)', hi: 'एस्प्रेसो (espresso)', mr: 'एस्प्रेसो (espresso)', ar: 'إسبريسو (espresso)' },
    color: '#795548',
  },
  bread: {
    word: 'Bread', phonetic: '/bred/', pos: 'noun',
    definition: 'A food made from baked dough of flour and water.',
    example: 'She baked fresh bread every morning.',
    translations: { en: 'Bread', fr: 'Pain', es: 'Pan', ja: 'パン (pan)', hi: 'रोटी (roti)', mr: 'पाव (paav)', ar: 'خبز (khubz)' },
    color: '#ff9800',
  },
  cheese: {
    word: 'Cheese', phonetic: '/tʃiːz/', pos: 'noun',
    definition: 'A food made from pressed milk curds, available in many varieties.',
    example: 'He sliced some cheese for the sandwich.',
    translations: { en: 'Cheese', fr: 'Fromage', es: 'Queso', ja: 'チーズ (chiizu)', hi: 'पनीर (paneer)', mr: 'चीज (cheese)', ar: 'جبن (jubn)' },
    color: '#ffeb3b',
  },
  'ice cream': {
    word: 'Ice Cream', phonetic: '/ˈaɪs kriːm/', pos: 'noun',
    definition: 'A sweet frozen food made from milk or cream.',
    example: 'The children enjoyed ice cream on a hot day.',
    translations: { en: 'Ice Cream', fr: 'Glace', es: 'Helado', ja: 'アイスクリーム (aisukuriimu)', hi: 'आइसक्रीम (ice cream)', mr: 'आइस्क्रीम (ice cream)', ar: 'آيس كريم (ice cream)' },
    color: '#e91e8c',
  },
  pretzel: {
    word: 'Pretzel', phonetic: '/ˈpret.səl/', pos: 'noun',
    definition: 'A baked bread snack twisted into a knot shape, often salted.',
    example: 'He snacked on a pretzel while watching the game.',
    translations: { en: 'Pretzel', fr: 'Bretzel', es: 'Pretzel', ja: 'プレッツェル (puretstseru)', hi: 'प्रेट्जल (pretzel)', mr: 'प्रेट्झेल (pretzel)', ar: 'معقود الخبز (ma\'qud al-khubz)' },
    color: '#ff9800',
  },
  mushroom: {
    word: 'Mushroom', phonetic: '/ˈmʌʃ.ruːm/', pos: 'noun',
    definition: 'A type of fungus with a cap and stalk, often used in cooking.',
    example: 'She added mushrooms to the pasta sauce.',
    translations: { en: 'Mushroom', fr: 'Champignon', es: 'Champiñón', ja: 'きのこ (kinoko)', hi: 'मशरूम (mushroom)', mr: 'मशरूम (mushroom)', ar: 'فطر (futr)' },
    color: '#795548',
  },
  lemon: {
    word: 'Lemon', phonetic: '/ˈlem.ən/', pos: 'noun',
    definition: 'A yellow citrus fruit with a sour taste.',
    example: 'She squeezed lemon juice over the fish.',
    translations: { en: 'Lemon', fr: 'Citron', es: 'Limón', ja: 'レモン (remon)', hi: 'नींबू (nimbu)', mr: 'लिंबू (limbu)', ar: 'ليمون (laymun)' },
    color: '#ffeb3b',
  },
  strawberry: {
    word: 'Strawberry', phonetic: '/ˈstrɔː.bər.i/', pos: 'noun',
    definition: 'A sweet red berry with small seeds on its surface.',
    example: 'She topped the cake with fresh strawberries.',
    translations: { en: 'Strawberry', fr: 'Fraise', es: 'Fresa', ja: 'いちご (ichigo)', hi: 'स्ट्रॉबेरी (strawberry)', mr: 'स्ट्रॉबेरी (strawberry)', ar: 'فراولة (farawla)' },
    color: '#f44336',
  },
  grapes: {
    word: 'Grapes', phonetic: '/ɡreɪps/', pos: 'noun',
    definition: 'Small, round fruits that grow in clusters on vines.',
    example: 'She put a bunch of grapes in the fruit bowl.',
    translations: { en: 'Grapes', fr: 'Raisins', es: 'Uvas', ja: 'ぶどう (budou)', hi: 'अंगूर (angur)', mr: 'द्राक्षे (draksha)', ar: 'عنب (\'inab)' },
    color: '#9c27b0',
  },
  pineapple: {
    word: 'Pineapple', phonetic: '/ˈpaɪn.æp.əl/', pos: 'noun',
    definition: 'A large tropical fruit with a spiky outer skin and sweet yellow flesh.',
    example: 'He cut the pineapple and served it as dessert.',
    translations: { en: 'Pineapple', fr: 'Ananas', es: 'Piña', ja: 'パイナップル (painappuru)', hi: 'अनानास (ananas)', mr: 'अननस (ananas)', ar: 'أناناس (ananas)' },
    color: '#ffeb3b',
  },
  watermelon: {
    word: 'Watermelon', phonetic: '/ˈwɔː.tə.mel.ən/', pos: 'noun',
    definition: 'A large fruit with green skin and sweet red flesh.',
    example: 'They ate watermelon at the picnic.',
    translations: { en: 'Watermelon', fr: 'Pastèque', es: 'Sandía', ja: 'スイカ (suika)', hi: 'तरबूज़ (tarbooz)', mr: 'टरबूज (tarbooz)', ar: 'بطيخ (battikh)' },
    color: '#4caf50',
  },
  egg: {
    word: 'Egg', phonetic: '/eɡ/', pos: 'noun',
    definition: 'An oval object laid by hens, used as food.',
    example: 'She fried two eggs for breakfast.',
    translations: { en: 'Egg', fr: 'Œuf', es: 'Huevo', ja: '卵 (tamago)', hi: 'अंडा (anda)', mr: 'अंडे (ande)', ar: 'بيضة (bayda)' },
    color: '#ffeb3b',
  },
  milk: {
    word: 'Milk', phonetic: '/mɪlk/', pos: 'noun',
    definition: 'A white liquid produced by mammals, used as a drink and in cooking.',
    example: 'She poured milk into the cereal bowl.',
    translations: { en: 'Milk', fr: 'Lait', es: 'Leche', ja: '牛乳 (gyuunyuu)', hi: 'दूध (dudh)', mr: 'दूध (dudh)', ar: 'حليب (halib)' },
    color: '#9e9e9e',
  },
  rice: {
    word: 'Rice', phonetic: '/raɪs/', pos: 'noun',
    definition: 'A grain crop that is a staple food for much of the world.',
    example: 'He cooked a pot of rice for dinner.',
    translations: { en: 'Rice', fr: 'Riz', es: 'Arroz', ja: 'ご飯 (gohan)', hi: 'चावल (chawal)', mr: 'भात (bhat)', ar: 'أرز (aruzz)' },
    color: '#9e9e9e',
  },
  noodles: {
    word: 'Noodles', phonetic: '/ˈnuː.dəlz/', pos: 'noun',
    definition: 'Thin strips of pasta or dough used in soups and stir-fries.',
    example: 'She made a bowl of noodle soup.',
    translations: { en: 'Noodles', fr: 'Nouilles', es: 'Fideos', ja: 'ラーメン (raamen)', hi: 'नूडल (noodle)', mr: 'नूडल्स (noodles)', ar: 'شعرية (sha\'iriyya)' },
    color: '#ff9800',
  },

  // ── Nature ───────────────────────────────────────────────────────────────
  flower: {
    word: 'Flower', phonetic: '/ˈflaʊ.ər/', pos: 'noun',
    definition: 'The colourful part of a plant that contains the reproductive organs.',
    example: 'She picked a bouquet of wild flowers.',
    translations: { en: 'Flower', fr: 'Fleur', es: 'Flor', ja: '花 (hana)', hi: 'फूल (phool)', mr: 'फूल (phool)', ar: 'زهرة (zahra)' },
    color: '#e91e8c',
  },
  tree: {
    word: 'Tree', phonetic: '/triː/', pos: 'noun',
    definition: 'A tall plant with a wooden trunk, branches, and leaves.',
    example: 'The children played under the shade of the tree.',
    translations: { en: 'Tree', fr: 'Arbre', es: 'Árbol', ja: '木 (ki)', hi: 'पेड़ (ped)', mr: 'झाड (jhad)', ar: 'شجرة (shajara)' },
    color: '#4caf50',
  },
  leaf: {
    word: 'Leaf', phonetic: '/liːf/', pos: 'noun',
    definition: 'A flat, green part of a plant that grows from a stem.',
    example: 'The autumn leaves turned red and gold.',
    translations: { en: 'Leaf', fr: 'Feuille', es: 'Hoja', ja: '葉 (ha)', hi: 'पत्ता (patta)', mr: 'पान (paan)', ar: 'ورقة (waraqa)' },
    color: '#4caf50',
  },
  grass: {
    word: 'Grass', phonetic: '/ɡrɑːs/', pos: 'noun',
    definition: 'A type of plant with narrow green leaves, covering lawns and fields.',
    example: 'The children ran barefoot on the grass.',
    translations: { en: 'Grass', fr: 'Herbe', es: 'Hierba', ja: '草 (kusa)', hi: 'घास (ghaas)', mr: 'गवत (gavat)', ar: 'عشب (\'ushb)' },
    color: '#4caf50',
  },
  rock: {
    word: 'Rock', phonetic: '/rɒk/', pos: 'noun',
    definition: 'A hard natural material made of minerals, forming part of the earth.',
    example: 'He skipped a flat rock across the pond.',
    translations: { en: 'Rock', fr: 'Rocher', es: 'Roca', ja: '岩 (iwa)', hi: 'पत्थर (patthar)', mr: 'दगड (dagad)', ar: 'صخرة (sakhra)' },
    color: '#607d8b',
  },
  mountain: {
    word: 'Mountain', phonetic: '/ˈmaʊn.tɪn/', pos: 'noun',
    definition: 'A large natural elevation of the earth\'s surface rising abruptly.',
    example: 'They hiked to the top of the mountain.',
    translations: { en: 'Mountain', fr: 'Montagne', es: 'Montaña', ja: '山 (yama)', hi: 'पहाड़ (pahad)', mr: 'पर्वत (parvat)', ar: 'جبل (jabal)' },
    color: '#607d8b',
  },
  river: {
    word: 'River', phonetic: '/ˈrɪv.ər/', pos: 'noun',
    definition: 'A large natural flow of water that empties into the sea or a lake.',
    example: 'They canoed down the river.',
    translations: { en: 'River', fr: 'Rivière', es: 'Río', ja: '川 (kawa)', hi: 'नदी (nadi)', mr: 'नदी (nadi)', ar: 'نهر (nahr)' },
    color: '#2196f3',
  },
  beach: {
    word: 'Beach', phonetic: '/biːtʃ/', pos: 'noun',
    definition: 'A sandy or pebbly shore beside the sea.',
    example: 'The family spent the day at the beach.',
    translations: { en: 'Beach', fr: 'Plage', es: 'Playa', ja: 'ビーチ (biichi)', hi: 'समुद्र तट (samudra tat)', mr: 'किनारा (kinara)', ar: 'شاطئ (shati)' },
    color: '#ffeb3b',
  },
  cloud: {
    word: 'Cloud', phonetic: '/klaʊd/', pos: 'noun',
    definition: 'A visible mass of water droplets floating in the atmosphere.',
    example: 'Dark clouds gathered before the storm.',
    translations: { en: 'Cloud', fr: 'Nuage', es: 'Nube', ja: '雲 (kumo)', hi: 'बादल (badal)', mr: 'ढग (dhag)', ar: 'سحابة (sahaba)' },
    color: '#9e9e9e',
  },
  sun: {
    word: 'Sun', phonetic: '/sʌn/', pos: 'noun',
    definition: 'The star around which the earth orbits, providing light and heat.',
    example: 'The sun set over the ocean.',
    translations: { en: 'Sun', fr: 'Soleil', es: 'Sol', ja: '太陽 (taiyou)', hi: 'सूरज (suraj)', mr: 'सूर्य (surya)', ar: 'شمس (shams)' },
    color: '#ffeb3b',
  },
  butterfly: {
    word: 'Butterfly', phonetic: '/ˈbʌt.ə.flaɪ/', pos: 'noun',
    definition: 'An insect with large, colourful wings.',
    example: 'A butterfly landed on the flower.',
    translations: { en: 'Butterfly', fr: 'Papillon', es: 'Mariposa', ja: '蝶 (chou)', hi: 'तितली (titali)', mr: 'फुलपाखरू (phulpakhru)', ar: 'فراشة (farasha)' },
    color: '#e91e8c',
  },
  fish: {
    word: 'Fish', phonetic: '/fɪʃ/', pos: 'noun',
    definition: 'A cold-blooded vertebrate that lives in water and breathes through gills.',
    example: 'He caught a large fish in the lake.',
    translations: { en: 'Fish', fr: 'Poisson', es: 'Pez', ja: '魚 (sakana)', hi: 'मछली (machli)', mr: 'मासा (masa)', ar: 'سمكة (samaka)' },
    color: '#2196f3',
  },
  turtle: {
    word: 'Turtle', phonetic: '/ˈtɜː.tl/', pos: 'noun',
    definition: 'A reptile with a hard shell and slow movement.',
    example: 'A sea turtle swam near the coral reef.',
    translations: { en: 'Turtle', fr: 'Tortue', es: 'Tortuga', ja: 'カメ (kame)', hi: 'कछुआ (kachhua)', mr: 'कासव (kasav)', ar: 'سلحفاة (salhafa)' },
    color: '#4caf50',
  },
  rabbit: {
    word: 'Rabbit', phonetic: '/ˈræb.ɪt/', pos: 'noun',
    definition: 'A small mammal with long ears, kept as a pet or found in the wild.',
    example: 'The rabbit hopped around the garden.',
    translations: { en: 'Rabbit', fr: 'Lapin', es: 'Conejo', ja: 'ウサギ (usagi)', hi: 'खरगोश (khargosh)', mr: 'ससा (sasa)', ar: 'أرنب (arnab)' },
    color: '#9e9e9e',
  },
  duck: {
    word: 'Duck', phonetic: '/dʌk/', pos: 'noun',
    definition: 'A waterbird with a flat bill and webbed feet.',
    example: 'The ducks swam peacefully on the pond.',
    translations: { en: 'Duck', fr: 'Canard', es: 'Pato', ja: 'アヒル (ahiru)', hi: 'बतख (batakh)', mr: 'बदक (badak)', ar: 'بطة (batta)' },
    color: '#ff9800',
  },
  frog: {
    word: 'Frog', phonetic: '/frɒɡ/', pos: 'noun',
    definition: 'A small amphibian with smooth skin and long legs for jumping.',
    example: 'A frog jumped into the pond.',
    translations: { en: 'Frog', fr: 'Grenouille', es: 'Rana', ja: 'カエル (kaeru)', hi: 'मेंढक (mendhak)', mr: 'बेडूक (beduk)', ar: 'ضفدع (dafda\')' },
    color: '#4caf50',
  },

  // ── Buildings & Structures ────────────────────────────────────────────────
  house: {
    word: 'House', phonetic: '/haʊs/', pos: 'noun',
    definition: 'A building in which people live.',
    example: 'They moved into their new house last week.',
    translations: { en: 'House', fr: 'Maison', es: 'Casa', ja: '家 (ie)', hi: 'घर (ghar)', mr: 'घर (ghar)', ar: 'منزل (manzil)' },
    color: '#ff9800',
  },
  church: {
    word: 'Church', phonetic: '/tʃɜːrtʃ/', pos: 'noun',
    definition: 'A building used for Christian religious services.',
    example: 'The wedding was held at the old church.',
    translations: { en: 'Church', fr: 'Église', es: 'Iglesia', ja: '教会 (kyoukai)', hi: 'गिरजाघर (girjaaghar)', mr: 'चर्च (church)', ar: 'كنيسة (kanisa)' },
    color: '#9e9e9e',
  },
  castle: {
    word: 'Castle', phonetic: '/ˈkɑː.səl/', pos: 'noun',
    definition: 'A large medieval building with thick walls and towers for defence.',
    example: 'They visited a medieval castle on their trip.',
    translations: { en: 'Castle', fr: 'Château', es: 'Castillo', ja: '城 (shiro)', hi: 'महल (mahal)', mr: 'किल्ला (killa)', ar: 'قلعة (qal\'a)' },
    color: '#607d8b',
  },
  bridge: {
    word: 'Bridge', phonetic: '/brɪdʒ/', pos: 'noun',
    definition: 'A structure carrying a road or path across a river or gap.',
    example: 'They walked across the old stone bridge.',
    translations: { en: 'Bridge', fr: 'Pont', es: 'Puente', ja: '橋 (hashi)', hi: 'पुल (pul)', mr: 'पूल (pul)', ar: 'جسر (jisr)' },
    color: '#607d8b',
  },
  fountain: {
    word: 'Fountain', phonetic: '/ˈfaʊn.tɪn/', pos: 'noun',
    definition: 'A decorative structure that jets water into the air.',
    example: 'Children played around the fountain in the park.',
    translations: { en: 'Fountain', fr: 'Fontaine', es: 'Fuente', ja: '噴水 (funsui)', hi: 'फव्वारा (phawwara)', mr: 'कारंजे (karanje)', ar: 'نافورة (nafura)' },
    color: '#2196f3',
  },
  door: {
    word: 'Door', phonetic: '/dɔːr/', pos: 'noun',
    definition: 'A movable panel that opens and closes an entrance.',
    example: 'She knocked on the door before entering.',
    translations: { en: 'Door', fr: 'Porte', es: 'Puerta', ja: 'ドア (doa)', hi: 'दरवाज़ा (darwaza)', mr: 'दरवाजा (darwaja)', ar: 'باب (bab)' },
    color: '#795548',
  },
  window: {
    word: 'Window', phonetic: '/ˈwɪn.dəʊ/', pos: 'noun',
    definition: 'An opening in a wall or roof fitted with glass to let in light.',
    example: 'She opened the window to let in some fresh air.',
    translations: { en: 'Window', fr: 'Fenêtre', es: 'Ventana', ja: '窓 (mado)', hi: 'खिड़की (khidki)', mr: 'खिडकी (khidaki)', ar: 'نافذة (nafidha)' },
    color: '#2196f3',
  },
  staircase: {
    word: 'Staircase', phonetic: '/ˈsteər.keɪs/', pos: 'noun',
    definition: 'A flight of stairs inside or outside a building.',
    example: 'She walked up the staircase to the second floor.',
    translations: { en: 'Staircase', fr: 'Escalier', es: 'Escalera', ja: '階段 (kaidan)', hi: 'सीढ़ी (seedhi)', mr: 'जिना (jina)', ar: 'درج (daraj)' },
    color: '#607d8b',
  },

  // ── Household Miscellaneous ───────────────────────────────────────────────
  candle: {
    word: 'Candle', phonetic: '/ˈkæn.dl/', pos: 'noun',
    definition: 'A cylinder of wax with a wick that is burned to provide light.',
    example: 'She lit a candle during the power cut.',
    translations: { en: 'Candle', fr: 'Bougie', es: 'Vela', ja: 'ろうそく (rousoku)', hi: 'मोमबत्ती (mombatti)', mr: 'मेणबत्ती (menbatti)', ar: 'شمعة (sham\'a)' },
    color: '#ff9800',
  },
  mirror: {
    word: 'Mirror', phonetic: '/ˈmɪr.ər/', pos: 'noun',
    definition: 'A surface that reflects images, typically made of glass.',
    example: 'She looked at herself in the mirror before leaving.',
    translations: { en: 'Mirror', fr: 'Miroir', es: 'Espejo', ja: '鏡 (kagami)', hi: 'शीशा (shesha)', mr: 'आरसा (arasa)', ar: 'مرآة (mir\'at)' },
    color: '#9e9e9e',
  },
  pillow: {
    word: 'Pillow', phonetic: '/ˈpɪl.əʊ/', pos: 'noun',
    definition: 'A soft cushion used to support the head while sleeping.',
    example: 'She fluffed her pillow before going to sleep.',
    translations: { en: 'Pillow', fr: 'Oreiller', es: 'Almohada', ja: '枕 (makura)', hi: 'तकिया (takiya)', mr: 'उशी (ushi)', ar: 'وسادة (wisada)' },
    color: '#9e9e9e',
  },
  curtain: {
    word: 'Curtain', phonetic: '/ˈkɜː.tɪn/', pos: 'noun',
    definition: 'A piece of fabric hanging at a window to block light or provide privacy.',
    example: 'She closed the curtains at night.',
    translations: { en: 'Curtain', fr: 'Rideau', es: 'Cortina', ja: 'カーテン (kaaten)', hi: 'पर्दा (parda)', mr: 'पडदा (padada)', ar: 'ستارة (sitara)' },
    color: '#e91e8c',
  },
  carpet: {
    word: 'Carpet', phonetic: '/ˈkɑː.pɪt/', pos: 'noun',
    definition: 'A thick fabric floor covering.',
    example: 'They laid a new carpet in the living room.',
    translations: { en: 'Carpet', fr: 'Tapis', es: 'Alfombra', ja: 'カーペット (kaapetto)', hi: 'कालीन (kaleen)', mr: 'गालिचा (galicha)', ar: 'سجادة (sajjada)' },
    color: '#795548',
  },
  lamp: {
    word: 'Lamp', phonetic: '/læmp/', pos: 'noun',
    definition: 'A device for giving light, especially one with an electric bulb.',
    example: 'She switched on the bedside lamp.',
    translations: { en: 'Lamp', fr: 'Lampe', es: 'Lámpara', ja: 'ランプ (ranpu)', hi: 'लैम्प (lamp)', mr: 'दिवा (diva)', ar: 'مصباح (misbah)' },
    color: '#ffeb3b',
  },
  shelf: {
    word: 'Shelf', phonetic: '/ʃelf/', pos: 'noun',
    definition: 'A flat surface fixed to a wall or frame for storing objects.',
    example: 'She arranged the books on the shelf.',
    translations: { en: 'Shelf', fr: 'Étagère', es: 'Estante', ja: '棚 (tana)', hi: 'शेल्फ (shelf)', mr: 'शेल्फ (shelf)', ar: 'رف (raff)' },
    color: '#795548',
  },
  trash: {
    word: 'Trash Can', phonetic: '/træʃ kæn/', pos: 'noun',
    definition: 'A container for collecting and disposing of rubbish.',
    example: 'She threw the empty bottle into the trash can.',
    translations: { en: 'Trash Can', fr: 'Poubelle', es: 'Papelera', ja: 'ゴミ箱 (gomibako)', hi: 'कूड़ेदान (kuddan)', mr: 'कचरापेटी (kachrapeeti)', ar: 'سلة المهملات (sallat al-muhmalat)' },
    color: '#9e9e9e',
  },
  pen: {
    word: 'Pen', phonetic: '/pen/', pos: 'noun',
    definition: 'An instrument for writing or drawing with ink.',
    example: 'She signed the letter with a pen.',
    translations: { en: 'Pen', fr: 'Stylo', es: 'Bolígrafo', ja: 'ペン (pen)', hi: 'कलम (kalam)', mr: 'पेन (pen)', ar: 'قلم (qalam)' },
    color: '#212121',
  },
  pencil: {
    word: 'Pencil', phonetic: '/ˈpen.sɪl/', pos: 'noun',
    definition: 'A thin stick of graphite in a wooden case, used for writing or drawing.',
    example: 'He sharpened his pencil before drawing.',
    translations: { en: 'Pencil', fr: 'Crayon', es: 'Lápiz', ja: '鉛筆 (enpitsu)', mr: 'पेन्सिल (pencil)', hi: 'पेंसिल (pencil)', ar: 'قلم رصاص (qalam rasas)' },
    color: '#ffeb3b',
  },
  notebook: {
    word: 'Notebook', phonetic: '/ˈnəʊt.bʊk/', pos: 'noun',
    definition: 'A small book with blank or ruled pages for writing notes.',
    example: 'She wrote her ideas in a notebook.',
    translations: { en: 'Notebook', fr: 'Cahier', es: 'Cuaderno', ja: 'ノート (nooto)', hi: 'नोटबुक (notebook)', mr: 'वही (vahi)', ar: 'دفتر (daftar)' },
    color: '#3f51b5',
  },
  envelope: {
    word: 'Envelope', phonetic: '/ˈen.və.ləʊp/', pos: 'noun',
    definition: 'A flat paper container used for sending letters.',
    example: 'She put the letter in an envelope and sealed it.',
    translations: { en: 'Envelope', fr: 'Enveloppe', es: 'Sobre', ja: '封筒 (fuutou)', hi: 'लिफाफा (lifafa)', mr: 'पाकीट (pakit)', ar: 'مظروف (mazruf)' },
    color: '#ff9800',
  },
  bag: {
    word: 'Bag', phonetic: '/bæɡ/', pos: 'noun',
    definition: 'A flexible container with an opening at the top for carrying things.',
    example: 'She packed her lunch in a bag.',
    translations: { en: 'Bag', fr: 'Sac', es: 'Bolsa', ja: 'バッグ (baggu)', hi: 'थैला (thela)', mr: 'पिशवी (pishvi)', ar: 'حقيبة (haqiba)' },
    color: '#607d8b',
  },
  rope: {
    word: 'Rope', phonetic: '/rəʊp/', pos: 'noun',
    definition: 'A thick string made by twisting fibres together.',
    example: 'He tied the boat to the dock with a rope.',
    translations: { en: 'Rope', fr: 'Corde', es: 'Cuerda', ja: 'ロープ (roopu)', hi: 'रस्सी (rassi)', mr: 'दोरी (dori)', ar: 'حبل (habl)' },
    color: '#ff9800',
  },
  box: {
    word: 'Box', phonetic: '/bɒks/', pos: 'noun',
    definition: 'A container with a flat base and sides, typically square or rectangular.',
    example: 'She packed her belongings into boxes.',
    translations: { en: 'Box', fr: 'Boîte', es: 'Caja', ja: '箱 (hako)', hi: 'डिब्बा (dibba)', mr: 'खोका (khoka)', ar: 'صندوق (sunduq)' },
    color: '#795548',
  },
  flag: {
    word: 'Flag', phonetic: '/flæɡ/', pos: 'noun',
    definition: 'A piece of cloth with a distinctive design representing a country.',
    example: 'The flag was raised during the ceremony.',
    translations: { en: 'Flag', fr: 'Drapeau', es: 'Bandera', ja: '旗 (hata)', hi: 'झंडा (jhanda)', mr: 'झेंडा (jhenda)', ar: 'علم (\'alam)' },
    color: '#f44336',
  },
  trophy: {
    word: 'Trophy', phonetic: '/ˈtrəʊ.fi/', pos: 'noun',
    definition: 'A cup or award given as a prize for winning a competition.',
    example: 'The team held up the trophy after winning.',
    translations: { en: 'Trophy', fr: 'Trophée', es: 'Trofeo', ja: 'トロフィー (torofii)', hi: 'ट्रॉफी (trophy)', mr: 'ट्रॉफी (trophy)', ar: 'كأس (ka\'s)' },
    color: '#ff9800',
  },
  map: {
    word: 'Map', phonetic: '/mæp/', pos: 'noun',
    definition: 'A diagrammatic representation of an area showing roads, cities, and features.',
    example: 'She studied the map before starting the hike.',
    translations: { en: 'Map', fr: 'Carte', es: 'Mapa', ja: '地図 (chizu)', hi: 'नक्शा (naksha)', mr: 'नकाशा (nakasha)', ar: 'خريطة (kharita)' },
    color: '#ff9800',
  },
};

// Auto-generate a basic vocabulary entry for any word detected by MobileNet
// that isn't in our pre-built dictionaries
function autoGenVocab(rawLabel) {
  // Parse label: "tabby, tabby cat" → "Tabby"
  const clean = rawLabel.split(',')[0].trim();
  const word = clean.charAt(0).toUpperCase() + clean.slice(1);
  return {
    word,
    phonetic: '',
    pos: 'noun',
    definition: `A ${clean} identified by the camera's AI recognition system.`,
    example: `There is a ${clean} in view.`,
    translations: {
      en: word, fr: '—', es: '—', ja: '—', hi: '—', mr: '—', ar: '—',
    },
    color: '#9c27b0',
    autoGenerated: true,
  };
}

// TTS language codes for SpeechSynthesis
const TTS_LANG = {
  en: 'en-US',
  fr: 'fr-FR',
  es: 'es-ES',
  ja: 'ja-JP',
  hi: 'hi-IN',
  mr: 'mr-IN',
  ar: 'ar-SA',
};

function getVocab(label) {
  const key = label.toLowerCase();
  if (VOCABULARY[key]) return VOCABULARY[key];
  if (COCO_FALLBACKS[key]) {
    return {
      word: COCO_FALLBACKS[key].word,
      phonetic: '',
      pos: 'noun',
      definition: `A ${COCO_FALLBACKS[key].word.toLowerCase()} detected in the environment.`,
      example: `There is a ${COCO_FALLBACKS[key].word.toLowerCase()} nearby.`,
      translations: COCO_FALLBACKS[key].translations,
      color: '#e91e8c',
    };
  }
  if (EXTENDED_VOCABULARY[key]) return EXTENDED_VOCABULARY[key];
  return null;
}

// Used by MobileNet results — tries harder with partial matching + auto-gen fallback
function getVocabForMnet(rawLabel) {
  // Normalise: take first part before comma, lowercase
  const parts = rawLabel.toLowerCase().split(',');
  for (const part of parts) {
    const key = part.trim();
    // Exact match in any dictionary
    if (VOCABULARY[key]) return VOCABULARY[key];
    if (EXTENDED_VOCABULARY[key]) return EXTENDED_VOCABULARY[key];
    if (COCO_FALLBACKS[key]) {
      const fb = COCO_FALLBACKS[key];
      return { word: fb.word, phonetic: '', pos: 'noun', definition: `A ${fb.word.toLowerCase()}.`, example: `There is a ${fb.word.toLowerCase()} nearby.`, translations: fb.translations, color: '#9c27b0' };
    }
    // Partial match — check if any known key is contained in the label or vice versa
    for (const dict of [VOCABULARY, EXTENDED_VOCABULARY]) {
      for (const [k, v] of Object.entries(dict)) {
        if (key.includes(k) || k.includes(key)) return v;
      }
    }
  }
  // Auto-generate for completely unknown labels
  return autoGenVocab(rawLabel);
}

function getAllVocabKeys() {
  return [...Object.keys(VOCABULARY), ...Object.keys(EXTENDED_VOCABULARY)];
}
